name: Create Release and Build Executable

on:
  push:
    branches: [ master ] # Trigger on push to the master branch

permissions:
  contents: write # Needed to create releases and upload assets

jobs:
  build-and-release:
    runs-on: windows-latest # Use Windows because of winreg dependency

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Or your preferred Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: pwsh # Use PowerShell on Windows runner

    - name: Build executable with PyInstaller
      run: pyinstaller --name CricketWidget --onefile --windowed --icon=cricket_icon.ico cricket_widget_fluent.py
      shell: pwsh

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: commit-${{ github.sha }} # Tag release with commit SHA
        name: Release ${{ github.sha }}
        body: |
          Automated release for commit ${{ github.sha }}
        files: dist/CricketWidget.exe # Path to the built executable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the default GitHub token 