name: Create Release and Build Executable

on:
  push:
    branches: [ master ] # Trigger on push to the master branch

permissions:
  contents: write # Needed to create releases and upload assets

jobs:
  build-and-release:
    runs-on: windows-latest # Use Windows for building the NSIS installer

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Or your preferred Node.js version

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8 # Or your preferred pnpm version
        run_install: false

    - name: Install dependencies
      run: pnpm install
      shell: pwsh # Use PowerShell on Windows runner

    - name: Build Electron App
      run: pnpm dist
      shell: pwsh

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }} # Tag release with run number (e.g., v1, v2)
        name: Release v${{ github.run_number }}
        body: |
          Automated release build.
        files: release/CricketWidget Setup*.exe # Path to the built NSIS installer
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the default GitHub token 